"""Arm the recording: park the mistake counter at 4/5 so your live correction fires it.

    python bench/demo_setup.py          # arm
    python bench/demo_setup.py --status # what state is it in
    python bench/demo_setup.py --reset  # unarm, put everything back

The notes are written through learn.save_mistake_note — the same function the
live path uses — so the demo is the real mechanism at 4/5, not a mock-up of it.
Nothing here is committed data: the corrections are generated by this file, so
the repo never carries a prebuilt corpus of someone's personal facts.
"""
import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from symbio import constants          # noqa: E402
from symbio.app import learn          # noqa: E402

TRAINABLE = "Qwen/Qwen3-8B-MLX-4bit"

# Four ordinary corrections. Deliberately not about the keyboard: the fifth one
# — the one recorded live — is the fact the golden set checks for, so it has to
# be absent from everything that came before or the demo proves nothing.
SEED = [
    dict(original_query="What timezone am I in?",
         wrong_answer="You're in UTC.",
         correction="no, I'm in Melbourne",
         correct_answer="You're in Melbourne, so AEST (UTC+10, or UTC+11 in daylight saving).",
         severity=1),
    dict(original_query="What editor do I use?",
         wrong_answer="You use VS Code.",
         correction="wrong, I use Neovim",
         correct_answer="You use Neovim.",
         severity=2),
    dict(original_query="Which Python version should I target?",
         wrong_answer="Target Python 3.9 for compatibility.",
         correction="no, this machine runs 3.14",
         correct_answer="Target Python 3.14 — that's what's installed here.",
         severity=1),
    dict(original_query="How much RAM does my machine have?",
         wrong_answer="Most development machines have 32GB or more.",
         correction="incorrect, it's a 16GB M4",
         correct_answer="It's an Apple M4 with 16GB of unified memory.",
         severity=2),
]


def status():
    cfg = json.load(open(ROOT / "config.json"))
    thr = cfg.get("learn", {}).get("mistake_threshold", 5)
    n = learn.mistake_note_count()
    golden = ROOT / "golden_cases.json"
    print(f"  model            : {cfg['model_name']}")
    print(f"  mistake counter  : {n}/{thr}" + ("   <-- ARMED" if n == thr - 1 else ""))
    print(f"  auto_train       : {cfg.get('learn', {}).get('auto_train')}")
    print(f"  golden cases     : {len(json.load(open(golden))) if golden.exists() else 0}"
          + ("" if golden.exists() else "  (absent)"))
    print(f"  adapter          : {'present' if (constants.ADAPTER_DIR / 'adapter_config.json').exists() else 'none'}")
    return n, thr


def arm():
    cfg_path = ROOT / "config.json"
    cfg = json.load(open(cfg_path))

    if cfg["model_name"] != TRAINABLE:
        shutil.copy(cfg_path, ROOT / "config.json.bak.pre-demo")
        cfg["model_name"] = TRAINABLE
        # The adapter and the draft only line up with the Qwen3 tokenizer.
        cfg.setdefault("agent", {})["draft_model"] = "models/Qwen3-0.6B-4bit"
        cfg["agent"]["num_draft_tokens"] = 2
        json.dump(cfg, open(cfg_path, "w"), indent=2)
        print(f"  model -> {TRAINABLE} (trainable on 16GB; adapter + draft both match)")
        print(f"  previous config saved to config.json.bak.pre-demo")

    golden = ROOT / "golden_cases.json"
    if not golden.exists():
        shutil.copy(ROOT / "golden_cases.recording.json.example", golden)
        print(f"  golden_cases.json installed ({len(json.load(open(golden)))} cases)")

    constants.MISTAKES_DIR.mkdir(parents=True, exist_ok=True)
    have = learn.mistake_note_count()
    thr = cfg.get("learn", {}).get("mistake_threshold", 5)
    need = (thr - 1) - have
    if need <= 0:
        print(f"  counter already at {have}/{thr}; nothing seeded")
    else:
        for spec in SEED[:need]:
            p = learn.save_mistake_note(**spec)
            print(f"  seeded  {p.name}")
    print()
    status()


def reset():
    removed = 0
    for f in constants.MISTAKES_DIR.glob("*.md"):
        f.unlink(); removed += 1
    print(f"  removed {removed} mistake note(s)")
    bak = ROOT / "config.json.bak.pre-demo"
    if bak.exists():
        shutil.copy(bak, ROOT / "config.json")
        print("  config restored from config.json.bak.pre-demo")
    print()
    status()


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--reset", action="store_true")
    a = ap.parse_args()
    if a.status:
        status()
    elif a.reset:
        reset()
    else:
        arm()
        print(f"""
  ARMED. Now record:

    ./symb chat
    Huy : What keyboard layout do I use?          <- it guesses QWERTY, wrongly
    Huy : no, I use Colemak                       <- correction #5 of 5

  That fires, on camera:
    correction captured  -> notes/mistakes/ hits 5/5
    digested             -> training_data/train.jsonl  (boosted 3x)
    LoRA fine-tune       -> 25+ iters on the corrections
    golden set replayed  -> the Colemak cases must now pass
    rollback if worse    -> a regression restores the old adapter

  The second golden case asks the same fact a different way ("which layout
  should a new keyboard support?"). Passing both is the moment worth filming:
  it learned the fact, not the sentence.
""")
